spring:
  datasource:
    url: jdbc:mysql://${MYSQLSERVER:localhost:3306}/payment_db
    username: "app_user"
    password: "{cipher}d9fc108c58401c9bf95ec55b49173f7ab2f0100ae37dfd1bb931aec09e94a57f"
    driver-class-name: com.mysql.cj.jdbc.Driver


payment:
  message: "welcome to payment production environment updated4 APIS"
  contactDetails:
    name: "Naveen kerla"
    email: "kerlanaveen19@digiclassroom.com"
  onCallSupport:
    - 88888-77777
    - 99999-66666
